=== toyboxman/yummy-xml-UI/xml-UI/schema/TransportationSchema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Transportation">
        <xs:annotation>
            <xs:documentation>include configuration concerning networking setting</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="server" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element type="xs:string" name="host"/>
                            <xs:element type="xs:unsignedShort" name="port"/>
                            <xs:element type="xs:unsignedShort" name="timeout" maxOccurs="1" minOccurs="0" default="120"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="registration" maxOccurs="1" minOccurs="1">
                    <xs:complexType>
                        <xs:all>
                            <xs:element type="xs:string" name="prsCode"/>
                            <xs:element type="xs:string" name="terminalID"/>
                            <xs:element type="xs:string" name="unionPayID"/>
                            <xs:element type="xs:string" name="token"/>
                            <xs:element type="xs:string" name="branchno"/>
                            <xs:element type="xs:int" name="heartbeat"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="misc" maxOccurs="1" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="watchDog"  maxOccurs="1" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="checkInterval" type="xs:int" maxOccurs="1" minOccurs="1"/>
                                    </xs:sequence>
                                    <xs:attribute name="enabled" type="xs:boolean" default="true" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="bankCardPrefix" maxOccurs="1" minOccurs="0">
                                <xs:simpleType>
                                    <xs:list itemType='xs:string'/>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="allowCPU"  maxOccurs="1" minOccurs="0">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="period">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="start" type="xs:time"/>
                                                    <xs:element name="end" type="xs:time"/>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== toyboxman/yummy-xml-UI/xml-UI/huangshan-src/backend.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
xml配置文件是用来描述界面组件的关系,对应节点的定义请参照xsd文件
引用 http://www.freeformatter.com/xsd-generator.html
     http://www.w3schools.com/schema/schema_elements_ref.asp
     http://www.opinionatedgeek.com/DotNet/Tools/HTMLEncode/encode.aspx
-->

<Transportation
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='../schema/TransportationSchema.xsd'>
    <server>
        <host>10.10.1.14</host>
        <port>6973</port>
        <timeout>20</timeout>
    </server>
    <registration>
        <prsCode>sanlogin</prsCode>
        <terminalID>10455843</terminalID>
        <token>usjdfjksa75ks832okudsjd94877akjdua</token>
        <unionPayID>947341249002001</unionPayID>
        <branchno>{"HospitalId":"2301","CAOZUOYDM":"AUTO1","CAOZUOYXM":"zizhuji1"}</branchno>
        <heartbeat>600000</heartbeat> 
    </registration>
    <misc>
    	
    	<!--<watchDog enabled="true">
            <checkInterval>10</checkInterval>
        </watchDog> -->
        <bankCardPrefix>
            622953
            621778
            621526 
        </bankCardPrefix>
    </misc>
</Transportation>
